Repository cse110-fa22-group26/cse110-fa22-group26, pull requests merged in 2022-12, with the labels that each got.

#51 Fixing the E2E framework
  .gitignore
  jest-puppeteer.config.js
  package-lock.json
  package.json
  source/assets/Tests/unitTestSignUp.test.js
  source/signUp.html
Labels: enhancement, fixing, Testing

#75 Fixed message for username log in
  source/assets/scripts/login.js
  source/assets/styles/welcomePageStyling.css
  source/welcomePage.html
Labels: enhancement, JS, fixing

#77 fix task count function and progbar error for 0/0 task
  source/assets/scripts/main.js
Labels: bug, JS, fixing

#86 Test homepage
  source/__test__/homepage.test.js
Labels: Testing

#94 E2E tests fixed
  package.json
  source/__test__/E2ESignUP.test.js
  source/__test__/homepage.test.js
  source/package-lock.json
  source/package.json
Labels: fixing, Testing

#93 Finalize cicd
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  jest-puppeteer.config.js
  jest.config.js
  package-lock.json
  package.json
  source/__test__/E2ESignUP.test.js
Labels: enhancement, Testing
