Repository cse110-fa22-group26/cse110-fa22-group26, pull requests merged in 2022-11, with the labels that each got.

#24 JS loginPage
  source/assets/scripts/login.js
  source/assets/scripts/main.js
  source/assets/styles/signUp.css
  source/assets/styles/welcomePageStyling.css
  source/welcomePage.html
Labels: JS

#43 set up sign up test files
  .gitignore
  package-lock.json
  package.json
  source/assets/Tests/E2ESignUP.test.js
  source/assets/Tests/unitTestSignUp.test.js
  source/assets/scripts/signUp.js
  source/signUp.html
Labels: Testing

#58 update documentation for cicd phase2
  admin/cipipeline/phase2.drawio.png
  admin/cipipeline/phase2.md
  admin/cipipeline/phase2.mp4
Labels: documentation

#59 Homepage jsdoc update
  source/assets/scripts/login.js
  source/assets/scripts/main.js
  source/assets/scripts/signUp.js
Labels: documentation
